from pathlib import Path
from collections import OrderedDict

root = Path(__file__).resolve().parent

target_files = [
    root / "src" / "ui" / "main_window.ui",
    root / "src" / "ui" / "report.ui",
    root / "src" / "ui" / "student.ui",
    root / "src" / "ui" / "score.ui",
    root / "src" / "ui" / "subject.ui",
    root / "src" / "ui" / "teacher.ui",
    root / "src" / "ui" / "class.ui",
    root / "src" / "ui" / "login.ui",
    root / "src" / "views" / "base_view.py",
    root / "src" / "views" / "class_view.py",
    root / "src" / "views" / "student_view.py",
    root / "src" / "views" / "teacher_view.py",
    root / "src" / "views" / "subject_view.py",
    root / "src" / "views" / "score_view.py",
    root / "src" / "views" / "report_view.py",
    root / "src" / "controllers" / "auth_controller.py",
    root / "src" / "controllers" / "class_controller.py",
    root / "src" / "controllers" / "student_controller.py",
    root / "src" / "controllers" / "teacher_controller.py",
    root / "src" / "controllers" / "subject_controller.py",
    root / "src" / "controllers" / "score_controller.py",
    root / "src" / "controllers" / "report_controller.py",
    root / "src" / "main_window.py",
]

replacements = OrderedDict([
    ("Student Score Management System", "Quản lý điểm học sinh"),
    ("Welcome to Student Score Management System", "Chào mừng đến với hệ thống quản lý điểm học sinh"),
    ("Select a module to manage", "Chọn chức năng để quản lý"),
    ("Students", "Học sinh"),
    ("Teachers", "Giáo viên"),
    ("Subjects", "Môn học"),
    ("Classes", "Lớp học"),
    ("Scores", "Điểm"),
    ("Reports", "Báo cáo"),
    ("Exit", "Thoát"),
    ("Reports & Statistics", "Báo cáo & Thống kê"),
    ("📊 Student Score Reports & Statistics", "📊 Báo cáo & thống kê điểm học sinh"),
    ("Điểm trung bìnhs", "Điểm trung bình"),
    ("Total Students: 0", "Tổng số học sinh: 0"),
    ("Điểm trung bình: 0.0", "Điểm trung bình: 0.0"),
    ("High Score: 0.0", "Điểm cao nhất: 0.0"),
    ("Low Score: 0.0", "Điểm thấp nhất: 0.0"),
    ("Student ID", "Mã HS"),
    ("Student Name", "Tên học sinh"),
    ("Generate Plot", "Tạo biểu đồ"),
    ("Export Data As:", "Xuất dữ liệu thành:"),
    ("Export to Excel", "Xuất Excel"),
    ("Export to CSV", "Xuất CSV"),
    ("Close", "Đóng"),
    ("Search:", "Tìm kiếm:"),
    ("Enter student name or email...", "Nhập tên hoặc email học sinh..."),
    ("Enter class name...", "Nhập tên lớp..."),
    ("ID", "Mã"),
    ("Class Name", "Tên lớp"),
    ("Grade Level", "Khối"),
    ("Homeroom Teacher", "Giáo viên chủ nhiệm"),
    ("Created", "Ngày tạo"),
    ("Add Class", "Thêm lớp"),
    ("Enter subject name...", "Nhập tên môn học..."),
    ("Subject Name", "Tên môn học"),
    ("Code", "Mã"),
    ("Credit", "Số tín chỉ"),
    ("Add Subject", "Thêm môn học"),
    ("Enter teacher name...", "Nhập tên giáo viên..."),
    ("Department", "Bộ môn"),
    ("Add Teacher", "Thêm giáo viên"),
    ("Student:", "Học sinh:"),
    ("Subject", "Môn học"),
    ("Semester", "Học kỳ"),
    ("Rating", "Xếp loại"),
    ("Add Score", "Thêm điểm"),
    ("Calculate Average", "Tính trung bình"),
    ("Student Management", "Quản lý học sinh"),
    ("Subject Management", "Quản lý môn học"),
    ("Teacher Management", "Quản lý giáo viên"),
    ("Class Management", "Quản lý lớp học"),
    ("Score Management", "Quản lý điểm"),
    ("Student Score Management - Login", "Quản lý điểm học sinh - Đăng nhập"),
    ("📚 Student Score Management", "📚 Quản lý điểm học sinh"),
    ("Username:", "Tên đăng nhập:"),
    ("Enter username", "Nhập tên đăng nhập"),
    ("Password:", "Mật khẩu:"),
    ("Enter password", "Nhập mật khẩu"),
    ("Login", "Đăng nhập"),
    ("QPushButton(\"Add\")", "QPushButton(\"Thêm\")"),
    ("QPushButton(\"Edit\")", "QPushButton(\"Sửa\")"),
    ("QPushButton(\"Delete\")", "QPushButton(\"Xóa\")"),
    ("QPushButton(\"Refresh\")", "QPushButton(\"Làm mới\")"),
    ("search_layout.addWidget(QLabel(\"Search:\"))", "search_layout.addWidget(QLabel(\"Tìm kiếm:\"))"),
    ("self.search_input.setPlaceholderText(\"Search...\")", "self.search_input.setPlaceholderText(\"Tìm kiếm...\")"),
    ("QMessageBox.warning(self, \"Error\", \"Please select an item!\")", "QMessageBox.warning(self, \"Lỗi\", \"Vui lòng chọn một mục!\")"),
    ("QMessageBox.critical(self, \"Error\",", "QMessageBox.critical(self, \"Lỗi\","),
    ("QMessageBox.information(self, \"Success\",", "QMessageBox.information(self, \"Thành công\","),
    ("QMessageBox.question(self, \"Confirm\",", "QMessageBox.question(self, \"Xác nhận\","),
    ("QMessageBox.warning(self, \"Error\", \"Please select a teacher!\")", "QMessageBox.warning(self, \"Lỗi\", \"Vui lòng chọn giáo viên!\")"),
    ("QMessageBox.warning(self, \"Error\", \"Please select a student!\")", "QMessageBox.warning(self, \"Lỗi\", \"Vui lòng chọn học sinh!\")"),
    ("QMessageBox.warning(self, \"Error\", \"Please select a score!\")", "QMessageBox.warning(self, \"Lỗi\", \"Vui lòng chọn điểm!\")"),
    ("QMessageBox.information(self, \"Info\", \"No scores found for this student!\")", "QMessageBox.information(self, \"Thông tin\", \"Không tìm thấy điểm cho học sinh này!\")"),
    ("QMessageBox.information(self, \"Result\", f\"Điểm trung bình: {avg:.2f}\\nRating: {rating}\")", "QMessageBox.information(self, \"Kết quả\", f\"Điểm trung bình: {avg:.2f}\\nXếp loại: {rating}\")"),
    ("New Class", "Thêm lớp"),
    ("Edit Class - ", "Sửa lớp - "),
    ("Name:", "Tên:"),
    ("Grade Level:", "Khối:"),
    ("Homeroom Teacher:", "Giáo viên chủ nhiệm:"),
    ("None", "Không chọn"),
    ("New Subject", "Thêm môn học"),
    ("Edit Subject - ", "Sửa môn học - "),
    ("Subject Name:", "Tên môn học:"),
    ("Credit:", "Số tín chỉ:"),
    ("New Teacher", "Thêm giáo viên"),
    ("Edit Teacher - ", "Sửa giáo viên - "),
    ("Department:", "Bộ môn:"),
    ("New Score", "Thêm điểm"),
    ("Edit Score", "Sửa điểm"),
    ("Student:", "Học sinh:"),
    ("Subject:", "Môn học:"),
    ("Score:", "Điểm:"),
    ("Semester:", "Học kỳ:"),
    ("Date of Birth:", "Ngày sinh:"),
    ("Address:", "Địa chỉ:"),
    ("Gender:", "Giới tính:"),
    ("Date of Birth (YYYY-MM-DD):", "Ngày sinh (YYYY-MM-DD):"),
    ("Male", "Nam"),
    ("Female", "Nữ"),
    ("Other", "Khác"),
    ("Select Teacher", "Chọn giáo viên"),
    ("Authentication", "Xác thực"),
    ("Save Excel File", "Lưu tệp Excel"),
    ("Excel Files (*.xlsx);;All Files (*)", "Tệp Excel (*.xlsx);;Tất cả tệp (*)"),
    ("Save CSV File", "Lưu tệp CSV"),
    ("CSV Files (*.csv);;All Files (*)", "Tệp CSV (*.csv);;Tất cả tệp (*)"),
    ("Save Plot", "Lưu biểu đồ"),
    ("PNG Files (*.png)", "Tệp PNG (*.png)"),
    ("Data exported to Excel successfully!", "Xuất dữ liệu sang Excel thành công!"),
    ("Data exported to CSV successfully!", "Xuất dữ liệu sang CSV thành công!"),
    ("Plot saved to ", "Đã lưu biểu đồ vào "),
    ("Failed to open student view: ", "Không thể mở giao diện quản lý học sinh: "),
    ("Failed to open teacher view: ", "Không thể mở giao diện quản lý giáo viên: "),
    ("Failed to open subject view: ", "Không thể mở giao diện quản lý môn học: "),
    ("Failed to open class view: ", "Không thể mở giao diện quản lý lớp học: "),
    ("Failed to open score view: ", "Không thể mở giao diện quản lý điểm: "),
    ("Failed to open report view: ", "Không thể mở giao diện báo cáo: "),
    ("Class added successfully!", "Thêm lớp thành công!"),
    ("Failed to add class: ", "Thêm lớp thất bại: "),
    ("Class updated successfully!", "Cập nhật lớp thành công!"),
    ("Failed to update class: ", "Cập nhật lớp thất bại: "),
    ("Are you sure you want to delete this class?", "Bạn có chắc chắn muốn xóa lớp học này?"),
    ("Class deleted successfully!", "Xóa lớp thành công!"),
    ("Failed to delete class: ", "Xóa lớp thất bại: "),
    ("Failed to load classes: ", "Tải lớp thất bại: "),
    ("Please select a class!", "Vui lòng chọn một lớp!"),
    ("Delete this class?", "Xóa lớp học này?"),
    ("Class Information", "Thông tin lớp học"),
    ("Student added successfully!", "Thêm học sinh thành công!"),
    ("Failed to add student: ", "Thêm học sinh thất bại: "),
    ("Student updated successfully!", "Cập nhật học sinh thành công!"),
    ("Failed to update student: ", "Cập nhật học sinh thất bại: "),
    ("Are you sure you want to delete this student?", "Bạn có chắc chắn muốn xóa học sinh này?"),
    ("Student deleted successfully!", "Xóa học sinh thành công!"),
    ("Failed to delete student: ", "Xóa học sinh thất bại: "),
    ("Failed to load students: ", "Tải học sinh thất bại: "),
    ("Please select a student!", "Vui lòng chọn học sinh!"),
    ("Delete this student?", "Xóa học sinh này?"),
    ("Student Information", "Thông tin học sinh"),
    ("Teacher added successfully!", "Thêm giáo viên thành công!"),
    ("Failed to add teacher: ", "Thêm giáo viên thất bại: "),
    ("Teacher updated successfully!", "Cập nhật giáo viên thành công!"),
    ("Failed to update teacher: ", "Cập nhật giáo viên thất bại: "),
    ("Are you sure you want to delete this teacher?", "Bạn có chắc chắn muốn xóa giáo viên này?"),
    ("Teacher deleted successfully!", "Xóa giáo viên thành công!"),
    ("Failed to delete teacher: ", "Xóa giáo viên thất bại: "),
    ("Failed to load teachers: ", "Tải giáo viên thất bại: "),
    ("Please select a teacher!", "Vui lòng chọn giáo viên!"),
    ("Delete this teacher?", "Xóa giáo viên này?"),
    ("Teacher Information", "Thông tin giáo viên"),
    ("Subject added successfully!", "Thêm môn học thành công!"),
    ("Failed to add subject: ", "Thêm môn học thất bại: "),
    ("Subject updated successfully!", "Cập nhật môn học thành công!"),
    ("Failed to update subject: ", "Cập nhật môn học thất bại: "),
    ("Are you sure you want to delete this subject?", "Bạn có chắc chắn muốn xóa môn học này?"),
    ("Subject deleted successfully!", "Xóa môn học thành công!"),
    ("Failed to delete subject: ", "Xóa môn học thất bại: "),
    ("Failed to load subjects: ", "Tải môn học thất bại: "),
    ("Please select a subject!", "Vui lòng chọn môn học!"),
    ("Delete this subject?", "Xóa môn học này?"),
    ("Subject Information", "Thông tin môn học"),
    ("Score added successfully!", "Thêm điểm thành công!"),
    ("Failed to add score: ", "Thêm điểm thất bại: "),
    ("Score updated successfully!", "Cập nhật điểm thành công!"),
    ("Failed to update score: ", "Cập nhật điểm thất bại: "),
    ("Are you sure you want to delete this score?", "Bạn có chắc chắn muốn xóa điểm này?"),
    ("Score deleted successfully!", "Xóa điểm thành công!"),
    ("Failed to delete score: ", "Xóa điểm thất bại: "),
    ("Failed to load scores: ", "Tải điểm thất bại: "),
    ("Score Information", "Thông tin điểm"),
    ("Score (0-10):", "Điểm (0-10):"),
    ("No scores found for this student!", "Không tìm thấy điểm cho học sinh này!"),
    ("Result", "Kết quả"),
    ("Điểm trung bình: ", "Điểm trung bình: "),
    ("Rating: ", "Xếp loại: "),
    ("Export student data to:", "Xuất dữ liệu học sinh sang:"),
    ("Failed to load average scores: ", "Tải điểm trung bình thất bại: "),
    ("Failed to export Excel: ", "Xuất Excel thất bại: "),
    ("Failed to export CSV: ", "Xuất CSV thất bại: "),
    ("Tệp CSV (*.csv);;Tất cả tệp (*)", "Tệp CSV (*.csv);;Tất cả tệp (*)"),
    ("Tệp Excel (*.xlsx);;Tất cả tệp (*)", "Tệp Excel (*.xlsx);;Tất cả tệp (*)"),
    ("Tệp PNG (*.png)", "Tệp PNG (*.png)"),
    ("Plot saved to ", "Đã lưu biểu đồ vào "),
    ("Data exported to ", "Dữ liệu đã được xuất đến "),
])

notes = []
changed = []
for path in target_files:
    if not path.exists():
        notes.append(f"Missing: {path}")
        continue
    text = path.read_text(encoding="utf-8")
    original = text
    for old, new in replacements.items():
        if old in text:
            text = text.replace(old, new)
    if text != original:
        path.write_text(text, encoding="utf-8")
        changed.append(path.relative_to(root))

for note in notes:
    print(note)
print("Changed:")
for c in changed:
    print(c)
