from .qt_compat import QtCore, QtGui, QtWidgets

class Ui_ClassWindow(object):
    def setupUi(self, ClassWindow):
        ClassWindow.setObjectName("ClassWindow")
        ClassWindow.resize(800, 500)
        self.centralwidget = QtWidgets.QWidget(ClassWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setObjectName("searchLayout")
        self.searchLayout.setContentsMargins(0, 0, 0, 12)
        self.searchLabel = QtWidgets.QLabel(self.centralwidget)
        self.searchLabel.setObjectName("searchLabel")
        self.searchLayout.addWidget(self.searchLabel)
        self.searchEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.searchEdit.setObjectName("searchEdit")
        self.searchEdit.setMinimumHeight(40)
        self.searchEdit.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.searchLayout.addWidget(self.searchEdit)
        self.mainLayout.addLayout(self.searchLayout)
        self.classTable = QtWidgets.QTableWidget(self.centralwidget)
        self.classTable.setObjectName("classTable")
        self.classTable.setColumnCount(5)
        self.classTable.setRowCount(0)
        self.classTable.setAlternatingRowColors(True)
        self.classTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        for i in range(5):
            item = QtWidgets.QTableWidgetItem()
            self.classTable.setHorizontalHeaderItem(i, item)
        self.mainLayout.addWidget(self.classTable)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.buttonLayout.setSpacing(14)
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setObjectName("addButton")
        self.addButton.setMinimumHeight(44)
        self.addButton.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.buttonLayout.addWidget(self.addButton)
        self.editButton = QtWidgets.QPushButton(self.centralwidget)
        self.editButton.setObjectName("editButton")
        self.editButton.setMinimumHeight(44)
        self.editButton.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.buttonLayout.addWidget(self.editButton)
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setObjectName("deleteButton")
        self.deleteButton.setMinimumHeight(44)
        self.deleteButton.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.buttonLayout.addWidget(self.deleteButton)
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setObjectName("refreshButton")
        self.refreshButton.setMinimumHeight(44)
        self.refreshButton.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.buttonLayout.addWidget(self.refreshButton)
        self.mainLayout.addLayout(self.buttonLayout)
        ClassWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(ClassWindow)
        QtCore.QMetaObject.connectSlotsByName(ClassWindow)

    def retranslateUi(self, ClassWindow):
        _translate = QtCore.QCoreApplication.translate
        ClassWindow.setWindowTitle(_translate("ClassWindow", "Quản lý lớp học"))
        self.searchLabel.setText(_translate("ClassWindow", "Tìm kiếm:"))
        self.searchEdit.setPlaceholderText(_translate("ClassWindow", "Nhập tên lớp..."))
        self.addButton.setText(_translate("ClassWindow", "Thêm lớp"))
        self.editButton.setText(_translate("ClassWindow", "Sửa"))
        self.deleteButton.setText(_translate("ClassWindow", "Xóa"))
        self.refreshButton.setText(_translate("ClassWindow", "Làm mới"))
        headers = ["Mã", "Tên lớp", "Khối", "Giáo viên chủ nhiệm", "Ngày tạo"]
        for idx, text in enumerate(headers):
            self.classTable.horizontalHeaderItem(idx).setText(_translate("ClassWindow", text))
