from .qt_compat import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.mainLayout.setContentsMargins(32, 24, 32, 24)
        self.welcomeLabel = QtWidgets.QLabel(self.centralwidget)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.welcomeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.welcomeLabel.setStyleSheet("font-size: 22px; font-weight: 700; margin: 12px;")
        self.mainLayout.addWidget(self.welcomeLabel)
        self.subtitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.subtitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.subtitleLabel.setStyleSheet("font-size: 14px; color: #4b5563; margin-bottom: 16px;")
        self.mainLayout.addWidget(self.subtitleLabel)
        self.buttonGrid = QtWidgets.QGridLayout()
        self.buttonGrid.setObjectName("buttonGrid")
        self.buttonGrid.setHorizontalSpacing(18)
        self.buttonGrid.setVerticalSpacing(18)
        self.studentButton = QtWidgets.QPushButton(self.centralwidget)
        self.studentButton.setObjectName("studentButton")
        self.studentButton.setMinimumSize(QtCore.QSize(0, 60))
        self.studentButton.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.buttonGrid.addWidget(self.studentButton, 0, 0, 1, 1)
        self.teacherButton = QtWidgets.QPushButton(self.centralwidget)
        self.teacherButton.setObjectName("teacherButton")
        self.teacherButton.setMinimumSize(QtCore.QSize(0, 60))
        self.teacherButton.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.buttonGrid.addWidget(self.teacherButton, 0, 1, 1, 1)
        self.subjectButton = QtWidgets.QPushButton(self.centralwidget)
        self.subjectButton.setObjectName("subjectButton")
        self.subjectButton.setMinimumSize(QtCore.QSize(0, 60))
        self.subjectButton.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.buttonGrid.addWidget(self.subjectButton, 1, 0, 1, 1)
        self.classButton = QtWidgets.QPushButton(self.centralwidget)
        self.classButton.setObjectName("classButton")
        self.classButton.setMinimumSize(QtCore.QSize(0, 60))
        self.classButton.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.buttonGrid.addWidget(self.classButton, 1, 1, 1, 1)
        self.scoreButton = QtWidgets.QPushButton(self.centralwidget)
        self.scoreButton.setObjectName("scoreButton")
        self.scoreButton.setMinimumSize(QtCore.QSize(0, 60))
        self.scoreButton.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.buttonGrid.addWidget(self.scoreButton, 2, 0, 1, 1)
        self.reportButton = QtWidgets.QPushButton(self.centralwidget)
        self.reportButton.setObjectName("reportButton")
        self.reportButton.setMinimumSize(QtCore.QSize(0, 60))
        self.reportButton.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.buttonGrid.addWidget(self.reportButton, 2, 1, 1, 1)
        self.mainLayout.addLayout(self.buttonGrid)
        self.verticalSpacer = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.mainLayout.addItem(self.verticalSpacer)
        self.logoutButton = QtWidgets.QPushButton(self.centralwidget)
        self.logoutButton.setObjectName("logoutButton")
        self.logoutButton.setMinimumSize(QtCore.QSize(0, 48))
        self.logoutButton.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.mainLayout.addWidget(self.logoutButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quản lý điểm học sinh"))
        self.welcomeLabel.setText(_translate("MainWindow", "Chào mừng đến với hệ thống quản lý điểm học sinh"))
        self.subtitleLabel.setText(_translate("MainWindow", "Chọn chức năng để quản lý"))
        self.studentButton.setText(_translate("MainWindow", "Học sinh"))
        self.teacherButton.setText(_translate("MainWindow", "Giáo viên"))
        self.subjectButton.setText(_translate("MainWindow", "Môn học"))
        self.classButton.setText(_translate("MainWindow", "Lớp học"))
        self.scoreButton.setText(_translate("MainWindow", "Điểm"))
        self.reportButton.setText(_translate("MainWindow", "Báo cáo"))
        self.logoutButton.setText(_translate("MainWindow", "Thoát"))
