from .qt_compat import QtCore, QtGui, QtWidgets

class Ui_ReportWindow(object):
    def setupUi(self, ReportWindow):
        ReportWindow.setObjectName("ReportWindow")
        ReportWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(ReportWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setObjectName("titleLabel")
        self.mainLayout.addWidget(self.titleLabel)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.averageTab = QtWidgets.QWidget()
        self.averageTab.setObjectName("averageTab")
        self.averageLayout = QtWidgets.QVBoxLayout(self.averageTab)
        self.averageLayout.setObjectName("averageLayout")
        self.statsLayout = QtWidgets.QHBoxLayout()
        self.statsLayout.setObjectName("statsLayout")
        self.totalLabel = QtWidgets.QLabel(self.averageTab)
        self.totalLabel.setObjectName("totalLabel")
        self.statsLayout.addWidget(self.totalLabel)
        self.avgLabel = QtWidgets.QLabel(self.averageTab)
        self.avgLabel.setObjectName("avgLabel")
        self.statsLayout.addWidget(self.avgLabel)
        self.highLabel = QtWidgets.QLabel(self.averageTab)
        self.highLabel.setObjectName("highLabel")
        self.statsLayout.addWidget(self.highLabel)
        self.lowLabel = QtWidgets.QLabel(self.averageTab)
        self.lowLabel.setObjectName("lowLabel")
        self.statsLayout.addWidget(self.lowLabel)
        self.averageLayout.addLayout(self.statsLayout)
        self.scoreTable = QtWidgets.QTableWidget(self.averageTab)
        self.scoreTable.setObjectName("scoreTable")
        self.scoreTable.setColumnCount(3)
        self.scoreTable.setRowCount(0)
        for i in range(3):
            item = QtWidgets.QTableWidgetItem()
            self.scoreTable.setHorizontalHeaderItem(i, item)
        self.averageLayout.addWidget(self.scoreTable)
        self.plotLayout = QtWidgets.QHBoxLayout()
        self.plotLayout.setObjectName("plotLayout")
        self.plotButton = QtWidgets.QPushButton(self.averageTab)
        self.plotButton.setObjectName("plotButton")
        self.plotLayout.addWidget(self.plotButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.plotLayout.addItem(spacerItem)
        self.averageLayout.addLayout(self.plotLayout)
        self.tabWidget.addTab(self.averageTab, "")
        self.exportTab = QtWidgets.QWidget()
        self.exportTab.setObjectName("exportTab")
        self.exportLayout = QtWidgets.QVBoxLayout(self.exportTab)
        self.exportLayout.setObjectName("exportLayout")
        self.exportLabel = QtWidgets.QLabel(self.exportTab)
        self.exportLabel.setObjectName("exportLabel")
        self.exportLayout.addWidget(self.exportLabel)
        self.exportButtonLayout = QtWidgets.QHBoxLayout()
        self.exportButtonLayout.setObjectName("exportButtonLayout")
        self.excelButton = QtWidgets.QPushButton(self.exportTab)
        self.excelButton.setObjectName("excelButton")
        self.exportButtonLayout.addWidget(self.excelButton)
        self.csvButton = QtWidgets.QPushButton(self.exportTab)
        self.csvButton.setObjectName("csvButton")
        self.exportButtonLayout.addWidget(self.csvButton)
        self.pdfButton = QtWidgets.QPushButton(self.exportTab)
        self.pdfButton.setObjectName("pdfButton")
        self.exportButtonLayout.addWidget(self.pdfButton)
        self.exportLayout.addLayout(self.exportButtonLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.exportLayout.addItem(spacerItem1)
        self.tabWidget.addTab(self.exportTab, "")
        self.mainLayout.addWidget(self.tabWidget)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setObjectName("refreshButton")
        self.buttonLayout.addWidget(self.refreshButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem2)
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setObjectName("closeButton")
        self.buttonLayout.addWidget(self.closeButton)
        self.mainLayout.addLayout(self.buttonLayout)
        ReportWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(ReportWindow)
        QtCore.QMetaObject.connectSlotsByName(ReportWindow)

    def retranslateUi(self, ReportWindow):
        _translate = QtCore.QCoreApplication.translate
        ReportWindow.setWindowTitle(_translate("ReportWindow", "Báo cáo & Thống kê"))
        self.titleLabel.setText(_translate("ReportWindow", "📊 Báo cáo điểm học sinh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.averageTab), _translate("ReportWindow", "Điểm trung bình"))
        self.totalLabel.setText(_translate("ReportWindow", "Tổng số học sinh: 0"))
        self.avgLabel.setText(_translate("ReportWindow", "Điểm trung bình: 0.0"))
        self.highLabel.setText(_translate("ReportWindow", "Điểm cao nhất: 0.0"))
        self.lowLabel.setText(_translate("ReportWindow", "Điểm thấp nhất: 0.0"))
        self.scoreTable.horizontalHeaderItem(0).setText(_translate("ReportWindow", "Mã HS"))
        self.scoreTable.horizontalHeaderItem(1).setText(_translate("ReportWindow", "Tên học sinh"))
        self.scoreTable.horizontalHeaderItem(2).setText(_translate("ReportWindow", "Điểm trung bình"))
        self.plotButton.setText(_translate("ReportWindow", "Tạo biểu đồ"))
        self.exportTab.setAccessibleName(_translate("ReportWindow", "exportTab"))
        self.exportLabel.setText(_translate("ReportWindow", "Xuất dữ liệu thành:"))
        self.excelButton.setText(_translate("ReportWindow", "Xuất Excel"))
        self.csvButton.setText(_translate("ReportWindow", "Xuất CSV"))
        self.pdfButton.setText(_translate("ReportWindow", "Xuất PDF"))
        self.refreshButton.setText(_translate("ReportWindow", "Làm mới"))
        self.closeButton.setText(_translate("ReportWindow", "Đóng"))
