from .qt_compat import QtCore, QtGui, QtWidgets

class Ui_StudentWindow(object):
    def setupUi(self, StudentWindow):
        StudentWindow.setObjectName("StudentWindow")
        StudentWindow.resize(900, 500)
        self.centralwidget = QtWidgets.QWidget(StudentWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setObjectName("searchLayout")
        self.searchLabel = QtWidgets.QLabel(self.centralwidget)
        self.searchLabel.setObjectName("searchLabel")
        self.searchLayout.addWidget(self.searchLabel)
        self.searchEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.searchEdit.setObjectName("searchEdit")
        self.searchLayout.addWidget(self.searchEdit)
        self.mainLayout.addLayout(self.searchLayout)
        self.studentTable = QtWidgets.QTableWidget(self.centralwidget)
        self.studentTable.setObjectName("studentTable")
        self.studentTable.setColumnCount(7)
        self.studentTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.studentTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentTable.setHorizontalHeaderItem(6, item)
        self.mainLayout.addWidget(self.studentTable)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setObjectName("addButton")
        self.buttonLayout.addWidget(self.addButton)
        self.editButton = QtWidgets.QPushButton(self.centralwidget)
        self.editButton.setObjectName("editButton")
        self.buttonLayout.addWidget(self.editButton)
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setObjectName("deleteButton")
        self.buttonLayout.addWidget(self.deleteButton)
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setObjectName("refreshButton")
        self.buttonLayout.addWidget(self.refreshButton)
        self.mainLayout.addLayout(self.buttonLayout)
        StudentWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(StudentWindow)
        QtCore.QMetaObject.connectSlotsByName(StudentWindow)

    def retranslateUi(self, StudentWindow):
        _translate = QtCore.QCoreApplication.translate
        StudentWindow.setWindowTitle(_translate("StudentWindow", "Quản lý học sinh"))
        self.searchLabel.setText(_translate("StudentWindow", "Tìm kiếm:"))
        self.searchEdit.setPlaceholderText(_translate("StudentWindow", "Nhập tên hoặc email học sinh..."))
        self.addButton.setText(_translate("StudentWindow", "Thêm học sinh"))
        self.editButton.setText(_translate("StudentWindow", "Sửa"))
        self.deleteButton.setText(_translate("StudentWindow", "Xóa"))
        self.refreshButton.setText(_translate("StudentWindow", "Làm mới"))
        self.studentTable.horizontalHeaderItem(0).setText(_translate("StudentWindow", "Mã"))
        self.studentTable.horizontalHeaderItem(1).setText(_translate("StudentWindow", "Tên"))
        self.studentTable.horizontalHeaderItem(2).setText(_translate("StudentWindow", "Ngày sinh"))
        self.studentTable.horizontalHeaderItem(3).setText(_translate("StudentWindow", "Giới tính"))
        self.studentTable.horizontalHeaderItem(4).setText(_translate("StudentWindow", "Email"))
        self.studentTable.horizontalHeaderItem(5).setText(_translate("StudentWindow", "SĐT"))
        self.studentTable.horizontalHeaderItem(6).setText(_translate("StudentWindow", "Địa chỉ"))
