from .qt_compat import QtCore, QtGui, QtWidgets

class Ui_ScoreWindow(object):
    def setupUi(self, ScoreWindow):
        ScoreWindow.setObjectName("ScoreWindow")
        ScoreWindow.resize(1000, 500)
        self.centralwidget = QtWidgets.QWidget(ScoreWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setObjectName("filterLayout")
        self.filterLayout.setContentsMargins(0, 0, 0, 12)
        self.filterLabel = QtWidgets.QLabel(self.centralwidget)
        self.filterLabel.setObjectName("filterLabel")
        self.filterLayout.addWidget(self.filterLabel)
        self.studentCombo = QtWidgets.QComboBox(self.centralwidget)
        self.studentCombo.setObjectName("studentCombo")
        self.studentCombo.setMinimumHeight(40)
        self.studentCombo.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.filterLayout.addWidget(self.studentCombo)
        self.mainLayout.addLayout(self.filterLayout)
        self.scoreTable = QtWidgets.QTableWidget(self.centralwidget)
        self.scoreTable.setObjectName("scoreTable")
        self.scoreTable.setColumnCount(6)
        self.scoreTable.setRowCount(0)
        self.scoreTable.setAlternatingRowColors(True)
        self.scoreTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        for i in range(6):
            item = QtWidgets.QTableWidgetItem()
            self.scoreTable.setHorizontalHeaderItem(i, item)
        self.mainLayout.addWidget(self.scoreTable)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.buttonLayout.setSpacing(14)
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setObjectName("addButton")
        self.addButton.setMinimumHeight(44)
        self.addButton.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.buttonLayout.addWidget(self.addButton)
        self.editButton = QtWidgets.QPushButton(self.centralwidget)
        self.editButton.setObjectName("editButton")
        self.editButton.setMinimumHeight(44)
        self.editButton.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.buttonLayout.addWidget(self.editButton)
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setObjectName("deleteButton")
        self.deleteButton.setMinimumHeight(44)
        self.deleteButton.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.buttonLayout.addWidget(self.deleteButton)
        self.calcButton = QtWidgets.QPushButton(self.centralwidget)
        self.calcButton.setObjectName("calcButton")
        self.calcButton.setMinimumHeight(44)
        self.calcButton.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.buttonLayout.addWidget(self.calcButton)
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setObjectName("refreshButton")
        self.refreshButton.setMinimumHeight(44)
        self.refreshButton.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.buttonLayout.addWidget(self.refreshButton)
        self.mainLayout.addLayout(self.buttonLayout)
        ScoreWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(ScoreWindow)
        QtCore.QMetaObject.connectSlotsByName(ScoreWindow)

    def retranslateUi(self, ScoreWindow):
        _translate = QtCore.QCoreApplication.translate
        ScoreWindow.setWindowTitle(_translate("ScoreWindow", "Quản lý điểm"))
        self.filterLabel.setText(_translate("ScoreWindow", "Học sinh:"))
        self.addButton.setText(_translate("ScoreWindow", "Thêm điểm"))
        self.editButton.setText(_translate("ScoreWindow", "Sửa"))
        self.deleteButton.setText(_translate("ScoreWindow", "Xóa"))
        self.calcButton.setText(_translate("ScoreWindow", "Tính trung bình"))
        self.refreshButton.setText(_translate("ScoreWindow", "Làm mới"))
        headers = ["Mã", "Học sinh", "Môn học", "Điểm", "Học kỳ", "Xếp loại"]
        for idx, text in enumerate(headers):
            self.scoreTable.horizontalHeaderItem(idx).setText(_translate("ScoreWindow", text))
