# -*- coding: utf-8 -*-
from .qt_compat import QtCore, QtGui, QtWidgets

class Ui_SubjectWindow(object):
    def setupUi(self, SubjectWindow):
        SubjectWindow.setObjectName("SubjectWindow")
        SubjectWindow.resize(700, 400)
        self.centralwidget = QtWidgets.QWidget(SubjectWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setObjectName("searchLayout")
        self.searchLayout.setContentsMargins(0, 0, 0, 12)
        self.searchLabel = QtWidgets.QLabel(self.centralwidget)
        self.searchLabel.setObjectName("searchLabel")
        self.searchLayout.addWidget(self.searchLabel)
        self.searchEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.searchEdit.setObjectName("searchEdit")
        self.searchEdit.setMinimumHeight(40)
        self.searchEdit.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.searchLayout.addWidget(self.searchEdit)
        self.mainLayout.addLayout(self.searchLayout)
        self.subjectTable = QtWidgets.QTableWidget(self.centralwidget)
        self.subjectTable.setObjectName("subjectTable")
        self.subjectTable.setColumnCount(5)
        self.subjectTable.setRowCount(0)
        self.subjectTable.setAlternatingRowColors(True)
        self.subjectTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        for i in range(5):
            item = QtWidgets.QTableWidgetItem()
            self.subjectTable.setHorizontalHeaderItem(i, item)
        self.mainLayout.addWidget(self.subjectTable)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.buttonLayout.setSpacing(14)
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setObjectName("addButton")
        self.addButton.setMinimumHeight(44)
        self.addButton.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.buttonLayout.addWidget(self.addButton)
        self.editButton = QtWidgets.QPushButton(self.centralwidget)
        self.editButton.setObjectName("editButton")
        self.editButton.setMinimumHeight(44)
        self.editButton.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.buttonLayout.addWidget(self.editButton)
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setObjectName("deleteButton")
        self.deleteButton.setMinimumHeight(44)
        self.deleteButton.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.buttonLayout.addWidget(self.deleteButton)
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setObjectName("refreshButton")
        self.refreshButton.setMinimumHeight(44)
        self.refreshButton.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.buttonLayout.addWidget(self.refreshButton)
        self.mainLayout.addLayout(self.buttonLayout)
        SubjectWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(SubjectWindow)
        QtCore.QMetaObject.connectSlotsByName(SubjectWindow)

    def retranslateUi(self, SubjectWindow):
        _translate = QtCore.QCoreApplication.translate
        SubjectWindow.setWindowTitle(_translate("SubjectWindow", "Quản lý môn học"))
        self.searchLabel.setText(_translate("SubjectWindow", "Tìm kiếm:"))
        self.searchEdit.setPlaceholderText(_translate("SubjectWindow", "Nhập tên hoặc mã môn học..."))
        self.addButton.setText(_translate("SubjectWindow", "Thêm"))
        self.editButton.setText(_translate("SubjectWindow", "Sửa"))
        self.deleteButton.setText(_translate("SubjectWindow", "Xóa"))
        self.refreshButton.setText(_translate("SubjectWindow", "Làm mới"))
        headers = ["Mã", "Tên", "Lớp học", "Ca học", "Ngày học"]
        for idx, text in enumerate(headers):
            self.subjectTable.horizontalHeaderItem(idx).setText(_translate("SubjectWindow", text))
